// Code generated by "stringer -type=CPUType"; DO NOT EDIT.

package m68k

import "fmt"

const _CPUType_name = "CPUTypeInvalidCPUType68000CPUType68010CPUType68EC020CPUType680020"

var _CPUType_index = [...]uint8{0, 14, 26, 38, 52, 65}

func (i CPUType) String() string {
	if i >= CPUType(len(_CPUType_index)-1) {
		return fmt.Sprintf("CPUType(%d)", i)
	}
	return _CPUType_name[_CPUType_index[i]:_CPUType_index[i+1]]
}
